name: Publish to VS Code Marketplace

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check version change
        id: check_version
        run: |
          NEW_VERSION=$(cat package.json | jq -r .version)

          git checkout HEAD^
          OLD_VERSION=$(cat package.json | jq -r .version)
          git checkout -

          if [ "${NEW_VERSION}" != "${OLD_VERSION}" ]; then
            echo "version_changed=true" >> ${GITHUB_OUTPUT}
            echo "Version changed from ${OLD_VERSION} to ${NEW_VERSION}"
          else
            echo "version_changed=false" >> ${GITHUB_OUTPUT}
            echo "::notice::Skipping publish (version unchanged)"
          fi

      - name: Set up Node
        if: steps.check_version.outputs.version_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        if: steps.check_version.outputs.version_changed == 'true'
        run: npm install

      - name: Package extension
        if: steps.check_version.outputs.version_changed == 'true'
        run: npx vsce package

      - name: Publish
        if: steps.check_version.outputs.version_changed == 'true'
        run: npx vsce publish -p ${{ secrets.VSCE_PAT }}
