name: Publish to VS Code Marketplace

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check version change
        id: check_version
        run: |
          NEW_VERSION=$(cat package.json | jq -r .version)

          git checkout HEAD^
          OLD_VERSION=$(cat package.json | jq -r .version)
          git checkout -

          if [ "$NEW_VERSION" != "$OLD_VERSION" ]; then
            echo "Version changed from $OLD_VERSION to $NEW_VERSION"
          else
            echo "::notice::Skipping publish (version unchanged)"
            exit 0
          fi

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Package extension
        run: npx vsce package

      - name: Publish
        run: npx vsce publish -p ${{ secrets.VSCE_PAT }}
